name: gdimmer
base: core18
version: git
summary: Laptop screen dimmer in Go
description: |
  Developed for use with Linux DEs that do not have
  build-in dimmers.

grade: devel
confinement: strict

plugs:
  system-files:
    read:
      - /sys/class/backlight/gmux_backlight/brightness
      - /sys/class/backlight/gmux_backlight/brightness
      - /sys/class/backlight/intel_backlight/max_brightness
      - /sys/class/backlight/intel_backlight/max_brightness
    write:
      - /sys/class/backlight/gmux_backlight/brightness
      - /sys/class/backlight/intel_backlight/brightness

parts:
  gdimmer:
    plugin: go
    source: .
    source-type: git

apps:
  gdimmer:
    command: gdimmer
